export const skills = [
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "Bootstrap",
    "JavaScript",
    "PHP",
    "Laravel",
    "React",
    "React Native",
    "Python",
    "MySQL",
    "Flutter",
    "Dart",
    "Kotlin",
    "Firebase",
    "REST API",
    "Context API",
    "Zustand",
    "React Navigation",
    "Riverpod",
    "StateNotifierProvider",
    "GoRouter",
    "Hive",
    "SQLite",
    "Local Storage",
    "Offline-First",
    "Machine Learning",
    "Cloud Computing",
    "Google Apps Script",
    "Google Cloud API",
    "Google Sheets",
    "Git",
    "GitHub"
];

export const tools = [
    "Visual Studio Code",
    "Postman",
    "Android Studio",
    "Cloudinary",
    "Figma",
    "Laragon",
    "GitHub",
    "XAMPP",
    "Composer",
    "NPM",
    "Vite",
    "Expo",
    "Jupyter Notebook",
    "Netlify",
    "Flutter Local Notifications"
];